// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyCj1RY48bHcfLCERNmGa7L1qfZz3JqNF9w',
    appId: '1:709668255326:web:5448f8ba84c4380a8a66cf',
    messagingSenderId: '709668255326',
    projectId: 'chat-application---test',
    authDomain: 'chat-application---test.firebaseapp.com',
    storageBucket: 'chat-application---test.appspot.com',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyBAublglf1jpNTnbyGe2Fvl4HhUuIWXi_c',
    appId: '1:709668255326:android:1a5b4d46723aa4648a66cf',
    messagingSenderId: '709668255326',
    projectId: 'chat-application---test',
    storageBucket: 'chat-application---test.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyB3oSbixslB68POiHWPqWO4MNbDdlrCCHE',
    appId: '1:709668255326:ios:1e9ccdc724a507e48a66cf',
    messagingSenderId: '709668255326',
    projectId: 'chat-application---test',
    storageBucket: 'chat-application---test.appspot.com',
    iosClientId:
        '709668255326-hbb03bglmh1ucgce28b4nft7big6re3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyB3oSbixslB68POiHWPqWO4MNbDdlrCCHE',
    appId: '1:709668255326:ios:1e9ccdc724a507e48a66cf',
    messagingSenderId: '709668255326',
    projectId: 'chat-application---test',
    storageBucket: 'chat-application---test.appspot.com',
    iosClientId:
        '709668255326-hbb03bglmh1ucgce28b4nft7big6re3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
